/*
App Name: Delivery Cashflow Dashboard
Version: 1.0.0
Generated By: Codex
Updated: 2026-05-27
*/

const APP_KEY = "deliveryCashflowDashboard.v1";

const StorageService = {
  load() {
    const raw = localStorage.getItem(APP_KEY);
    if (!raw) return createSeedData();
    try {
      return normalizeState(JSON.parse(raw));
    } catch {
      return createSeedData();
    }
  },
  save(state) {
    localStorage.setItem(APP_KEY, JSON.stringify(state));
  },
  clear() {
    localStorage.removeItem(APP_KEY);
  }
};

let state = StorageService.load();

const yen = new Intl.NumberFormat("ja-JP", {
  style: "currency",
  currency: "JPY",
  maximumFractionDigits: 0
});

const views = {
  home: document.querySelector("#homeView"),
  manage: document.querySelector("#manageView"),
  settings: document.querySelector("#settingsView")
};

const entryDialog = document.querySelector("#entryDialog");
const entryForm = document.querySelector("#entryForm");
const importFile = document.querySelector("#importFile");
const importDialog = document.querySelector("#importDialog");
const importModeForm = document.querySelector("#importModeForm");
const refreshButton = document.querySelector("#refreshButton");
const toast = document.querySelector("#toast");
let toastTimer;
let pendingImportState = null;

function createSeedData() {
  const now = new Date();
  const today = toDateInput(now);
  const add = (days) => {
    const date = new Date(now);
    date.setDate(date.getDate() + days);
    return toDateInput(date);
  };

  return {
    version: "1.0.0",
    balance: {
      amount: 18500,
      updatedAt: `${today}T09:12:00`,
      calculationMode: "ledger"
    },
    settings: {
      hourlyRate: 2000,
      averageDeliveriesPerHour: 3,
      maxDailyWorkHours: 10,
      maxWeeklyWorkDays: 5,
      warningThreshold: 5000
    },
    backup: {
      lastBackupAt: null,
      reminderDays: 7
    },
    payments: [
      { id: makeId(), name: "電気代", amount: 8000, date: add(-7), status: "planned" },
      { id: makeId(), name: "携帯料金", amount: 3000, date: add(3), status: "planned" },
      { id: makeId(), name: "クレカ", amount: 10000, date: add(8), status: "planned" },
      { id: makeId(), name: "家賃", amount: 50000, date: add(30), status: "planned" }
    ],
    incomes: [
      { id: makeId(), name: "配達報酬", amount: 25000, date: add(10) },
      { id: makeId(), name: "配達報酬", amount: 28000, date: add(17) }
    ]
  };
}

function normalizeState(data) {
  const payments = Array.isArray(data.payments) ? data.payments.map((item) => ({
    id: item.id || makeId(),
    name: item.name || "支払い",
    amount: Number(item.amount || 0),
    date: item.date || toDateInput(new Date()),
    status: item.status === "paid" ? "paid" : "planned"
  })) : [];
  const incomes = Array.isArray(data.incomes) ? data.incomes.map((item) => ({
    id: item.id || makeId(),
    name: item.name || "入金",
    amount: Number(item.amount || 0),
    date: item.date || toDateInput(new Date())
  })) : [];
  const legacyAmount = Number(data.balance?.amount || 0);
  const isLedgerMode = data.balance?.calculationMode === "ledger";
  const today = todayInput();
  const receivedTotal = sum(incomes.filter((income) => income.date <= today));
  const paidTotal = sum(payments.filter((payment) => payment.status === "paid"));
  const baseAmount = isLedgerMode ? legacyAmount : legacyAmount - receivedTotal + paidTotal;

  return {
    version: data.version || "1.0.0",
    balance: {
      amount: baseAmount,
      updatedAt: data.balance?.updatedAt || new Date().toISOString(),
      calculationMode: "ledger"
    },
    settings: {
      hourlyRate: Number(data.settings?.hourlyRate || 2000),
      averageDeliveriesPerHour: normalizeAverageDeliveries(data.settings),
      maxDailyWorkHours: Number(data.settings?.maxDailyWorkHours || 10),
      maxWeeklyWorkDays: clampNumber(data.settings?.maxWeeklyWorkDays ?? 5, 0, 7),
      warningThreshold: Number(data.settings?.warningThreshold || 5000)
    },
    backup: {
      lastBackupAt: data.backup?.lastBackupAt || null,
      reminderDays: clampNumber(data.backup?.reminderDays ?? 7, 0, 90)
    },
    payments,
    incomes
  };
}

function makeId() {
  return `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 8)}`;
}

function clampNumber(value, min, max) {
  const number = Number(value);
  if (!Number.isFinite(number)) return min;
  return Math.min(max, Math.max(min, number));
}

function normalizeAverageDeliveries(settings = {}) {
  if (settings.averageDeliveriesPerHour !== undefined) {
    return Number(settings.averageDeliveriesPerHour || 0);
  }
  if (settings.deliveryUnitPrice && settings.hourlyRate) {
    return Number((Number(settings.hourlyRate) / Number(settings.deliveryUnitPrice)).toFixed(1));
  }
  return 3;
}

function workHoursForAmount(amount) {
  return state.settings.hourlyRate > 0 ? amount / state.settings.hourlyRate : 0;
}

function deliveriesForHours(hours) {
  return Math.ceil(Math.max(0, hours) * Number(state.settings.averageDeliveriesPerHour || 0));
}

function deliveriesForAmount(amount) {
  return deliveriesForHours(workHoursForAmount(amount));
}

function toDateInput(date) {
  const local = new Date(date.getTime() - date.getTimezoneOffset() * 60000);
  return local.toISOString().slice(0, 10);
}

function parseLocalDate(value) {
  return new Date(`${value}T00:00:00`);
}

function todayInput() {
  return toDateInput(new Date());
}

function dayDiff(a, b) {
  const day = 86400000;
  return Math.floor((parseLocalDate(a) - parseLocalDate(b)) / day);
}

function formatDate(value) {
  const date = parseLocalDate(value);
  return `${date.getMonth() + 1}/${String(date.getDate()).padStart(2, "0")}`;
}

function formatDateTime(value) {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "未更新";
  return date.toLocaleString("ja-JP", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit"
  });
}

function paymentStatus(payment) {
  if (payment.status === "paid") return "支払い済み";
  return dayDiff(payment.date, todayInput()) < 0 ? "期限超過" : "予定";
}

function assessment(balanceAfter) {
  if (balanceAfter < 0) return "NG";
  if (balanceAfter <= state.settings.warningThreshold) return "注意";
  return "OK";
}

function currentBalance() {
  const today = todayInput();
  const receivedTotal = sum(state.incomes.filter((income) => income.date <= today));
  const paidTotal = sum(state.payments.filter((payment) => payment.status === "paid"));
  return state.balance.amount + receivedTotal - paidTotal;
}

function buildSimulation(untilDate) {
  const today = todayInput();
  let balance = currentBalance();
  const events = [];

  state.incomes.forEach((income) => {
    if (income.date > today && (!untilDate || income.date <= untilDate)) {
      events.push({ type: "income", date: income.date, amount: income.amount, name: income.name });
    }
  });

  state.payments
    .filter((payment) => payment.status !== "paid")
    .forEach((payment) => {
      if (!untilDate || payment.date <= untilDate) {
        events.push({ type: "payment", date: payment.date < today ? today : payment.date, amount: payment.amount, name: payment.name, id: payment.id });
      }
    });

  events.sort((a, b) => a.date.localeCompare(b.date) || (a.type === "income" ? -1 : 1));

  const rows = [{
    date: todayInput(),
    type: "start",
    name: "現在",
    amount: 0,
    balance,
    judgement: assessment(balance)
  }];

  events.forEach((event) => {
    balance += event.type === "income" ? event.amount : -event.amount;
    rows.push({
      ...event,
      balance,
      judgement: event.type === "payment" ? assessment(balance) : ""
    });
  });

  return rows;
}

function computeDashboard() {
  const today = todayInput();
  const unpaidPayments = state.payments.filter((payment) => payment.status !== "paid");
  const overdue = unpaidPayments.filter((payment) => dayDiff(payment.date, today) < 0);
  const futurePayments = unpaidPayments.filter((payment) => dayDiff(payment.date, today) >= 0);
  const nextIncome = state.incomes
    .filter((income) => income.date >= today)
    .sort((a, b) => a.date.localeCompare(b.date))[0];
  const nextIncomeDate = nextIncome?.date || addDays(today, 14);
  const rowsToNextIncome = buildSimulation(nextIncomeDate).filter((row) => row.type !== "income" || row.date !== nextIncomeDate);
  const minBalanceBeforeIncome = Math.min(...rowsToNextIncome.map((row) => row.balance));
  const needAmount = Math.max(0, -minBalanceBeforeIncome);
  const workHours = state.settings.hourlyRate > 0 ? needAmount / state.settings.hourlyRate : 0;
  const deliveryCount = deliveriesForAmount(needAmount);
  const remainingDays = Math.max(1, dayDiff(nextIncomeDate, today));
  const dailyNeed = needAmount / remainingDays;
  const balanceAgeDays = Math.max(0, Math.floor((Date.now() - new Date(state.balance.updatedAt).getTime()) / 86400000));
  const simulation = buildSimulation(addDays(today, 31));
  const balance = currentBalance();

  return {
    today,
    nextIncome,
    nextIncomeDate,
    overdue,
    futurePayments,
    needAmount,
    workHours,
    deliveryCount,
    dailyNeed,
    balanceAgeDays,
    simulation,
    balance
  };
}

function backupReminder() {
  const reminderDays = Number(state.backup?.reminderDays ?? 7);
  if (reminderDays <= 0) return null;
  if (!state.backup?.lastBackupAt) {
    return {
      due: true,
      days: null,
      message: "まだデータ保存が実行されていません。"
    };
  }

  const elapsedDays = Math.floor((Date.now() - new Date(state.backup.lastBackupAt).getTime()) / 86400000);
  if (elapsedDays < reminderDays) return null;

  return {
    due: true,
    days: elapsedDays,
    message: `前回のデータ保存から${elapsedDays}日経過しています。`
  };
}

function startOfWeek(value) {
  const date = parseLocalDate(value);
  const day = date.getDay() || 7;
  date.setDate(date.getDate() - day + 1);
  return toDateInput(date);
}

function weekLabel(startDate) {
  return `${formatDate(startDate)}週`;
}

function monthlySimplePlan() {
  const today = todayInput();
  const endDate = addDays(today, 30);
  const payments = state.payments.filter((payment) => payment.status !== "paid" && payment.date >= today && payment.date <= endDate);
  const incomes = state.incomes.filter((income) => income.date >= today && income.date <= endDate);
  const paymentTotal = sum(payments);
  const incomeTotal = sum(incomes);
  const neededSales = Math.max(0, paymentTotal - currentBalance() - incomeTotal);
  const estimatedWorkDays = (30 / 7) * Number(state.settings.maxWeeklyWorkDays || 0);
  const workdaySales = estimatedWorkDays > 0 ? neededSales / estimatedWorkDays : 0;
  const workdayHours = workHoursForAmount(workdaySales);

  return {
    paymentTotal,
    incomeTotal,
    neededSales,
    estimatedWorkDays,
    workdaySales,
    workdayHours,
    workdayDeliveries: deliveriesForHours(workdayHours)
  };
}

function earningCapacity() {
  const dailyHours = Number(state.settings.maxDailyWorkHours || 0);
  const weeklyDays = Number(state.settings.maxWeeklyWorkDays || 0);
  const hourlyRate = Number(state.settings.hourlyRate || 0);
  const deliveriesPerHour = Number(state.settings.averageDeliveriesPerHour || 0);

  return {
    dailySales: hourlyRate * dailyHours,
    weeklySales: hourlyRate * dailyHours * weeklyDays,
    dailyDeliveries: Math.ceil(deliveriesPerHour * dailyHours),
    weeklyDeliveries: Math.ceil(deliveriesPerHour * dailyHours * weeklyDays),
    weeklyHours: dailyHours * weeklyDays,
    averageUnitPrice: deliveriesPerHour > 0 ? hourlyRate / deliveriesPerHour : null
  };
}

function weeklyWorkPlan() {
  const today = todayInput();
  const weekCount = 5;
  const weeklyHours = Number(state.settings.maxDailyWorkHours || 0) * Number(state.settings.maxWeeklyWorkDays || 0);
  const weeklyCapacity = weeklyHours * Number(state.settings.hourlyRate || 0);
  const weeks = Array.from({ length: weekCount }, (_, index) => {
    const start = addDays(startOfWeek(today), index * 7);
    return {
      start,
      label: weekLabel(start),
      requiredSales: 0,
      capacitySales: weeklyCapacity
    };
  });

  const demands = shortageDemands(addDays(today, 34));
  let overflow = 0;

  demands.forEach((demand) => {
    let remaining = demand.amount;
    let weekIndex = weeks.findIndex((week, index) => {
      const nextStart = weeks[index + 1]?.start || addDays(week.start, 7);
      return demand.date >= week.start && demand.date < nextStart;
    });

    if (weekIndex < 0) weekIndex = weeks.length - 1;

    for (let index = weekIndex; index >= 0 && remaining > 0; index -= 1) {
      const available = Math.max(0, weeks[index].capacitySales - weeks[index].requiredSales);
      const assigned = Math.min(remaining, available);
      weeks[index].requiredSales += assigned;
      remaining -= assigned;
    }

    overflow += remaining;
  });

  return {
    weeks: weeks.map((week) => ({
      ...week,
      requiredHours: workHoursForAmount(week.requiredSales),
      requiredDeliveries: deliveriesForAmount(week.requiredSales),
      dailySales: Number(state.settings.maxWeeklyWorkDays || 0) > 0 ? week.requiredSales / Number(state.settings.maxWeeklyWorkDays || 0) : 0,
      dailyHours: Number(state.settings.maxWeeklyWorkDays || 0) > 0 ? workHoursForAmount(week.requiredSales) / Number(state.settings.maxWeeklyWorkDays || 0) : 0,
      dailyDeliveries: Number(state.settings.maxWeeklyWorkDays || 0) > 0 ? Math.ceil(deliveriesForAmount(week.requiredSales) / Number(state.settings.maxWeeklyWorkDays || 0)) : 0,
      isOverCapacity: week.requiredSales > weeklyCapacity
    })),
    weeklyHours,
    weeklyCapacity,
    overflow
  };
}

function shortageDemands(untilDate) {
  const rows = buildSimulation(untilDate);
  const demands = [];
  let currentPeak = 0;

  rows.forEach((row) => {
    const deficit = Math.max(0, -row.balance);
    if (deficit > currentPeak) {
      demands.push({
        date: row.date,
        amount: deficit - currentPeak,
        name: row.name
      });
      currentPeak = deficit;
    }
    if (row.balance >= 0) {
      currentPeak = 0;
    }
  });

  return demands;
}

function addDays(value, days) {
  const date = parseLocalDate(value);
  date.setDate(date.getDate() + days);
  return toDateInput(date);
}

function saveAndRender() {
  StorageService.save(state);
  render();
}

function render() {
  renderHome();
  renderManage();
  renderSettings();
}

function showToast(message) {
  clearTimeout(toastTimer);
  toast.textContent = message;
  toast.classList.add("is-visible");
  toastTimer = setTimeout(() => {
    toast.classList.remove("is-visible");
  }, 1800);
}

function refreshDashboard() {
  render();
  refreshButton.classList.remove("is-spinning");
  void refreshButton.offsetWidth;
  refreshButton.classList.add("is-spinning");
  showToast("再計算しました");
}

function renderHome() {
  const model = computeDashboard();
  const backupAlert = backupReminder();
  const overdueTotal = sum(model.overdue);
  const futureTotal = sum(model.futurePayments);
  const firstNegative = model.simulation.find((row) => row.balance < 0);
  const dangerous = dangerousPayments(model.simulation);

  views.home.innerHTML = `
    ${model.overdue.length ? `<div class="alert"><strong>期限超過があります</strong><span>${model.overdue.length}件、合計${yen.format(overdueTotal)}の支払いが未完了です。</span></div>` : ""}
    ${backupAlert ? `<div class="alert alert-info"><strong>データ保存</strong><span>${backupAlert.message}</span><button class="secondary-button" data-action="export-json" type="button">今すぐ保存</button></div>` : ""}
    ${model.balanceAgeDays >= 7 ? `<div class="alert"><strong>残高調整</strong><span>残高が7日以上調整されていません。</span></div>` : ""}
    <div class="quick-actions">
      <button class="primary-button" data-action="new-payment" type="button">支払い追加</button>
      <button class="secondary-button" data-action="new-income" type="button">入金追加</button>
    </div>
    <div class="hero-summary">
      <section class="need-panel ${model.needAmount > 0 ? "is-danger" : ""}">
        <p class="section-kicker">次回報酬までに必要</p>
        <div class="need-amount">${yen.format(model.needAmount)}</div>
        <p>${model.nextIncome ? `${formatDate(model.nextIncome.date)}の${model.nextIncome.name}まで` : "次回入金予定が未登録です"}</p>
        <div class="need-grid">
          <div><span>必要稼働</span><strong>${model.workHours.toFixed(1)}時間</strong></div>
          <div><span>件数換算</span><strong>${model.deliveryCount}件</strong></div>
          <div><span>必要売上/日</span><strong>${yen.format(model.dailyNeed)}</strong></div>
        </div>
      </section>
      <section class="balance-panel">
        <div>
          <p class="section-kicker">現在残高（自動計算）</p>
          <div class="balance-value">${yen.format(model.balance)}</div>
          <p class="meta">基準残高 ${yen.format(state.balance.amount)} / 最終調整 ${formatDateTime(state.balance.updatedAt)}</p>
        </div>
        <form class="balance-form" data-action="adjust-balance">
          <input name="actualBalance" type="number" min="0" step="1" inputmode="numeric" value="${model.balance}" aria-label="実際の残高">
          <button class="primary-button" type="submit">差額調整</button>
        </form>
        <p class="meta">実際の残高を入力すると、差額を「残高調整」の入金または支払いとして登録します。</p>
      </section>
    </div>

    <div class="summary-grid">
      ${metric("期限超過", `${model.overdue.length}件`, yen.format(overdueTotal), model.overdue.length ? "danger" : "")}
      ${metric("今後の支払い", `${model.futurePayments.length}件`, yen.format(futureTotal), "")}
      ${metric("必要稼働", `${model.workHours.toFixed(1)}時間`, `件数換算 ${model.deliveryCount}件`, model.needAmount ? "warn" : "")}
      ${metric("最初の不足日", firstNegative ? formatDate(firstNegative.date) : "なし", firstNegative ? yen.format(firstNegative.balance) : "予測内OK", firstNegative ? "danger" : "")}
    </div>

    <div class="content-grid">
      <section class="section-panel">
        <div class="section-header"><h2>期限超過一覧</h2></div>
        ${renderOverdueList(model.overdue)}
      </section>
      <section class="section-panel">
        <div class="section-header"><h2>要注意支払い</h2></div>
        ${renderDangerList(dangerous)}
      </section>
      <section class="section-panel">
        <div class="section-header"><h2>未来残高予測</h2></div>
        ${renderTimeline(model.simulation, firstNegative)}
      </section>
      <section class="section-panel">
        <div class="section-header"><h2>期間サマリー</h2></div>
        ${renderPeriodSummary()}
      </section>
      <section class="section-panel">
        <div class="section-header"><h2>30日単純計画</h2></div>
        ${renderMonthlySimplePlan()}
      </section>
      <section class="section-panel">
        <div class="section-header"><h2>週別必要稼働</h2></div>
        ${renderWeeklyWorkPlan()}
      </section>
    </div>
  `;
}

function metric(label, value, detail, tone) {
  return `<section class="metric ${tone}"><p class="section-kicker">${label}</p><strong>${value}</strong><p class="meta">${detail}</p></section>`;
}

function sum(items) {
  return items.reduce((total, item) => total + Number(item.amount || 0), 0);
}

function renderOverdueList(items) {
  if (!items.length) return `<p class="empty">期限超過の支払いはありません。</p>`;
  return `<div class="list-stack">${items
    .sort((a, b) => a.date.localeCompare(b.date))
    .map((item) => `
      <article class="list-item">
        <div class="list-line"><strong>${escapeHtml(item.name)}</strong><span class="amount">${yen.format(item.amount)}</span></div>
        <div class="status-row"><span class="badge danger">${formatDate(item.date)}</span><span class="badge danger">超過 ${Math.abs(dayDiff(item.date, todayInput()))}日</span></div>
        <div class="row-actions"><span></span><button class="text-button" data-action="toggle-paid" data-type="payment" data-id="${item.id}" type="button">支払い済み</button></div>
      </article>
    `).join("")}</div>`;
}

function dangerousPayments(simulation) {
  const byPayment = simulation
    .filter((row) => row.type === "payment" && row.judgement !== "OK")
    .map((row) => ({
      ...row,
      shortage: Math.max(0, -row.balance),
      requiredHours: state.settings.hourlyRate > 0 ? Math.max(0, -row.balance) / state.settings.hourlyRate : 0,
      requiredDeliveries: deliveriesForAmount(Math.max(0, -row.balance))
    }));

  const overdueRows = state.payments
    .filter((payment) => payment.status !== "paid" && paymentStatus(payment) === "期限超過")
    .map((payment) => ({
      date: payment.date,
      name: payment.name,
      amount: payment.amount,
      balance: currentBalance() - payment.amount,
      judgement: "期限超過",
      shortage: Math.max(0, payment.amount - currentBalance()),
      requiredHours: state.settings.hourlyRate > 0 ? Math.max(0, payment.amount - currentBalance()) / state.settings.hourlyRate : 0,
      requiredDeliveries: deliveriesForAmount(Math.max(0, payment.amount - currentBalance())),
      id: payment.id
    }));

  return [...overdueRows, ...byPayment]
    .sort((a, b) => rankJudgement(a.judgement) - rankJudgement(b.judgement) || a.date.localeCompare(b.date))
    .slice(0, 8);
}

function rankJudgement(value) {
  return { "期限超過": 0, NG: 1, "注意": 2, OK: 3 }[value] ?? 4;
}

function renderDangerList(items) {
  if (!items.length) return `<p class="empty">要注意の支払いはありません。</p>`;
  return `<div class="list-stack">${items.map((item) => `
    <article class="list-item">
      <div class="list-line"><strong>${escapeHtml(item.name)}</strong><span class="amount">${yen.format(item.amount)}</span></div>
      <div class="status-row">
        <span class="badge ${badgeTone(item.judgement)}">${item.judgement}</span>
        <span class="badge">${formatDate(item.date)}</span>
        <span class="badge">${item.shortage > 0 ? `不足 ${yen.format(item.shortage)}` : `予測 ${yen.format(item.balance)}`}</span>
        <span class="badge">必要稼働 ${item.requiredHours.toFixed(1)}h</span>
        <span class="badge">件数換算 ${item.requiredDeliveries}件</span>
      </div>
      ${item.id ? `<div class="row-actions"><span></span><button class="text-button" data-action="toggle-paid" data-type="payment" data-id="${item.id}" type="button">支払い済み</button></div>` : ""}
    </article>
  `).join("")}</div>`;
}

function renderTimeline(rows, firstNegative) {
  return `<div class="timeline">${rows.slice(0, 14).map((row) => {
    const isFirstNegative = firstNegative && row.date === firstNegative.date && row.balance === firstNegative.balance;
    const label = row.type === "start" ? "現在" : row.type === "income" ? "入金後" : "支払い後";
    return `
      <article class="timeline-item ${isFirstNegative ? "danger" : ""}">
        <div class="list-line"><strong>${row.type === "start" ? "現在" : formatDate(row.date)} ${label}</strong><span class="amount ${row.balance < 0 ? "negative" : ""}">${yen.format(row.balance)}</span></div>
        <div class="status-row">
          <span class="badge">${escapeHtml(row.name)}</span>
          ${row.judgement ? `<span class="badge ${badgeTone(row.judgement)}">${row.judgement}</span>` : ""}
          ${isFirstNegative ? `<span class="badge danger">最初のマイナス</span>` : ""}
        </div>
      </article>
    `;
  }).join("")}</div>`;
}

function renderPeriodSummary() {
  const periods = [
    ["今日", todayInput()],
    ["次回入金まで", computeDashboard().nextIncomeDate],
    ["2週間", addDays(todayInput(), 14)],
    ["1か月", addDays(todayInput(), 31)]
  ];

  return `<div class="list-stack">${periods.map(([label, date]) => {
    const rows = buildSimulation(date);
    const min = Math.min(...rows.map((row) => row.balance));
    const shortage = Math.max(0, -min);
    const margin = Math.max(0, min);
    const hours = state.settings.hourlyRate > 0 ? shortage / state.settings.hourlyRate : 0;
    const deliveries = deliveriesForHours(hours);
    return `
      <article class="list-item">
        <div class="list-line"><strong>${label}</strong><span class="amount">${shortage ? `不足 ${yen.format(shortage)}` : `余裕 ${yen.format(margin)}`}</span></div>
        <div class="status-row"><span class="badge">必要稼働 ${hours.toFixed(1)}h</span><span class="badge">件数換算 ${deliveries}件</span></div>
      </article>
    `;
  }).join("")}</div>`;
}

function renderMonthlySimplePlan() {
  const plan = monthlySimplePlan();
  return `<div class="list-stack">
    <article class="list-item">
      <div class="list-line"><strong>30日支払い合計</strong><span class="amount">${yen.format(plan.paymentTotal)}</span></div>
      <div class="status-row"><span class="badge">入金予定 ${yen.format(plan.incomeTotal)}</span><span class="badge">必要売上 ${yen.format(plan.neededSales)}</span></div>
    </article>
    <article class="list-item">
      <div class="list-line"><strong>1稼働日あたり</strong><span class="amount">${plan.estimatedWorkDays > 0 ? yen.format(plan.workdaySales) : "未設定"}</span></div>
      <div class="status-row"><span class="badge">想定稼働日数 ${plan.estimatedWorkDays.toFixed(1)}日</span><span class="badge">必要稼働 ${plan.workdayHours.toFixed(1)}h</span><span class="badge">件数換算 ${plan.workdayDeliveries}件</span></div>
    </article>
  </div>`;
}

function renderWeeklyWorkPlan() {
  const plan = weeklyWorkPlan();
  if (!plan.weeks.some((week) => week.requiredSales > 0) && plan.overflow === 0) {
    return `<p class="empty">現在の予測では前倒し稼働は不要です。</p>`;
  }

  return `<div class="list-stack">
    ${plan.overflow > 0 ? `<div class="alert"><strong>週キャパ超過</strong><span>${yen.format(plan.overflow)}分は表示期間より前から準備が必要です。</span></div>` : ""}
    ${plan.weeks.map((week) => `
      <article class="list-item">
        <div class="list-line"><strong>${week.label}</strong><span class="amount">${yen.format(week.requiredSales)}</span></div>
        <div class="status-row">
          <span class="badge">必要稼働 ${week.requiredHours.toFixed(1)}h</span>
          <span class="badge">件数換算 ${week.requiredDeliveries}件</span>
          <span class="badge">1稼働日 ${yen.format(week.dailySales)}</span>
          <span class="badge">1稼働日 ${week.dailyHours.toFixed(1)}h / ${week.dailyDeliveries}件</span>
          <span class="badge">上限 ${plan.weeklyHours.toFixed(1)}h</span>
        </div>
      </article>
    `).join("")}
  </div>`;
}

function badgeTone(value) {
  if (value === "OK") return "ok";
  if (value === "注意") return "warn";
  if (value === "NG" || value === "期限超過") return "danger";
  return "";
}

function renderManage() {
  views.manage.innerHTML = `
    <div class="toolbar">
      <button class="primary-button" data-action="new-payment" type="button">支払いを追加</button>
      <button class="secondary-button" data-action="new-income" type="button">入金を追加</button>
      <button class="danger-button" data-action="clear-ledger" type="button">入出金を全削除</button>
    </div>
    <div class="manage-grid">
      <section class="section-panel">
        <div class="section-header"><h2>支払い一覧</h2></div>
        ${renderPayments()}
      </section>
      <section class="section-panel">
        <div class="section-header"><h2>入金予定</h2></div>
        ${renderIncomes()}
      </section>
    </div>
  `;
}

function renderPayments() {
  if (!state.payments.length) return `<p class="empty">支払いは登録されていません。</p>`;
  const simulation = buildSimulation(addDays(todayInput(), 365));
  return `<div class="list-stack">${state.payments
    .slice()
    .sort((a, b) => a.date.localeCompare(b.date))
    .map((payment) => {
      const row = simulation.find((item) => item.id === payment.id);
      const judge = payment.status === "paid" ? "OK" : row?.judgement || assessment(currentBalance() - payment.amount);
      return `
        <article class="list-item">
          <div class="list-line"><strong>${payment.status === "paid" ? "✓" : "○"} ${escapeHtml(payment.name)}</strong><span class="amount">${yen.format(payment.amount)}</span></div>
          <div class="status-row">
            <span class="badge">${formatDate(payment.date)}</span>
            <span class="badge ${badgeTone(paymentStatus(payment))}">${paymentStatus(payment)}</span>
            <span class="badge ${badgeTone(judge)}">${judge}</span>
          </div>
          <div class="row-actions">
            <button class="text-button" data-action="toggle-paid" data-type="payment" data-id="${payment.id}" type="button">${payment.status === "paid" ? "未払いへ" : "支払い済み"}</button>
            <span>
              <button class="text-button" data-action="edit" data-type="payment" data-id="${payment.id}" type="button">編集</button>
              <button class="text-button" data-action="duplicate" data-type="payment" data-id="${payment.id}" type="button">複製</button>
              <button class="text-button" data-action="delete" data-type="payment" data-id="${payment.id}" type="button">削除</button>
            </span>
          </div>
        </article>
      `;
    }).join("")}</div>`;
}

function renderIncomes() {
  if (!state.incomes.length) return `<p class="empty">入金予定は登録されていません。</p>`;
  return `<div class="list-stack">${state.incomes
    .slice()
    .sort((a, b) => a.date.localeCompare(b.date))
    .map((income) => `
      <article class="list-item">
        <div class="list-line"><strong>${escapeHtml(income.name)}</strong><span class="amount">${yen.format(income.amount)}</span></div>
        <div class="status-row"><span class="badge">${formatDate(income.date)}</span></div>
        <div class="row-actions">
          <span></span>
          <span>
            <button class="text-button" data-action="edit" data-type="income" data-id="${income.id}" type="button">編集</button>
            <button class="text-button" data-action="duplicate" data-type="income" data-id="${income.id}" type="button">複製</button>
            <button class="text-button" data-action="delete" data-type="income" data-id="${income.id}" type="button">削除</button>
          </span>
        </div>
      </article>
    `).join("")}</div>`;
}

function renderSettings() {
  const backupAlert = backupReminder();
  const lastBackupText = state.backup?.lastBackupAt ? formatDateTime(state.backup.lastBackupAt) : "未実行";
  const capacity = earningCapacity();
  views.settings.innerHTML = `
    <section class="form-panel">
      <h2>設定</h2>
      <form class="settings-grid" data-action="save-settings">
        <label>平均売上/時間
          <input name="hourlyRate" type="number" min="0" step="1" inputmode="numeric" value="${state.settings.hourlyRate}">
        </label>
        <label>平均件数/時間
          <input name="averageDeliveriesPerHour" type="number" min="0" step="0.1" inputmode="decimal" value="${state.settings.averageDeliveriesPerHour}">
        </label>
        <label>1日の最大稼働時間
          <input name="maxDailyWorkHours" type="number" min="0" max="24" step="0.5" inputmode="decimal" value="${state.settings.maxDailyWorkHours}">
        </label>
        <label>週の最大稼働日数
          <input name="maxWeeklyWorkDays" type="number" min="0" max="7" step="1" inputmode="numeric" value="${state.settings.maxWeeklyWorkDays}">
        </label>
        <label>注意判定閾値
          <input name="warningThreshold" type="number" min="0" step="1" inputmode="numeric" value="${state.settings.warningThreshold}">
        </label>
        <label>データ保存アラート頻度（日）
          <input name="backupReminderDays" type="number" min="0" max="90" step="1" inputmode="numeric" value="${state.backup?.reminderDays ?? 7}">
        </label>
        <p class="meta">0日にするとアラートを表示しません。最大90日です。</p>
        <button class="primary-button" type="submit">設定を保存</button>
      </form>
    </section>
    <section class="form-panel">
      <h2>予想売上</h2>
      <div class="summary-grid">
        ${metric("1日あたり", yen.format(capacity.dailySales), `${capacity.dailyDeliveries}件 / ${state.settings.maxDailyWorkHours}h`, "")}
        ${metric("週あたり", yen.format(capacity.weeklySales), `${capacity.weeklyDeliveries}件 / ${capacity.weeklyHours.toFixed(1)}h`, "")}
        ${metric("平均単価", capacity.averageUnitPrice === null ? "未設定" : yen.format(capacity.averageUnitPrice), "平均売上/時間 ÷ 平均件数/時間", "")}
      </div>
    </section>
    <section class="form-panel">
      <h2>データ保存・読込</h2>
      ${backupAlert ? `<div class="alert alert-info"><strong>データ保存</strong><span>${backupAlert.message}</span></div>` : ""}
      <div class="toolbar">
        <button class="secondary-button" data-action="export-json" type="button">データ保存</button>
        <button class="secondary-button" data-action="import-json" type="button">データ読込</button>
        <button class="danger-button" data-action="reset-data" type="button">データ初期化</button>
      </div>
      <p class="meta">全データをJSON形式で保存、復元できます。最終データ保存: ${lastBackupText}</p>
    </section>
  `;
}

function openEntryDialog(type, item) {
  document.querySelector("#entryType").value = type;
  document.querySelector("#entryId").value = item?.id || "";
  document.querySelector("#entryName").value = item?.name || (type === "payment" ? "支払い" : "配達報酬");
  document.querySelector("#entryAmount").value = item?.amount || "";
  document.querySelector("#entryDate").value = item?.date || todayInput();
  document.querySelector("#dialogTitle").textContent = type === "payment" ? "支払い登録" : "入金登録";
  entryDialog.showModal();
}

function handleAction(target) {
  const action = target.dataset.action;
  const type = target.dataset.type;
  const id = target.dataset.id;
  if (!action) return;

  if (action === "new-payment") openEntryDialog("payment");
  if (action === "new-income") openEntryDialog("income");
  if (action === "edit") openEntryDialog(type, findItem(type, id));
  if (action === "duplicate") duplicateItem(type, id);
  if (action === "delete") deleteItem(type, id);
  if (action === "toggle-paid") togglePaid(id);
  if (action === "export-json") exportJson();
  if (action === "import-json") importFile.click();
  if (action === "reset-data") resetData();
  if (action === "clear-ledger") clearLedger();
}

function findItem(type, id) {
  return (type === "payment" ? state.payments : state.incomes).find((item) => item.id === id);
}

function duplicateItem(type, id) {
  const source = findItem(type, id);
  if (!source) return;
  const copy = { ...source, id: makeId(), name: `${source.name} コピー`, status: source.status || "planned" };
  if (type === "payment") state.payments.push(copy);
  else state.incomes.push(copy);
  saveAndRender();
}

function deleteItem(type, id) {
  if (!confirm("削除しますか？")) return;
  if (type === "payment") state.payments = state.payments.filter((item) => item.id !== id);
  else state.incomes = state.incomes.filter((item) => item.id !== id);
  saveAndRender();
}

function togglePaid(id) {
  const payment = state.payments.find((item) => item.id === id);
  if (!payment) return;
  payment.status = payment.status === "paid" ? "planned" : "paid";
  saveAndRender();
}

function adjustBalance(actualBalance) {
  const calculatedBalance = currentBalance();
  const difference = Number(actualBalance) - calculatedBalance;
  if (difference === 0) {
    state.balance.updatedAt = new Date().toISOString();
    saveAndRender();
    showToast("差額はありません");
    return;
  }

  const adjustment = {
    id: makeId(),
    name: "残高調整",
    amount: Math.abs(difference),
    date: todayInput()
  };

  if (difference > 0) {
    state.incomes.push(adjustment);
    showToast("差額を収入として調整しました");
  } else {
    state.payments.push({ ...adjustment, status: "paid" });
    showToast("差額を支出として調整しました");
  }

  state.balance.updatedAt = new Date().toISOString();
  saveAndRender();
}

function exportJson() {
  state.backup.lastBackupAt = new Date().toISOString();
  StorageService.save(state);
  const blob = new Blob([JSON.stringify(state, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = `delivery-cashflow-${todayInput()}.json`;
  anchor.click();
  URL.revokeObjectURL(url);
  render();
  showToast("データを保存しました");
}

function resetData() {
  if (!confirm("すべてのデータを初期化しますか？")) return;
  StorageService.clear();
  state = createSeedData();
  saveAndRender();
}

function clearLedger() {
  if (!confirm("支払いと入金予定をすべて削除し、現在残高も0にします。設定は残ります。実行しますか？")) return;
  state.payments = [];
  state.incomes = [];
  state.balance.amount = 0;
  state.balance.updatedAt = new Date().toISOString();
  saveAndRender();
  showToast("入出金データと残高を削除しました");
}

function appendImportedData(imported) {
  state.payments = [
    ...state.payments,
    ...imported.payments.map((payment) => ({ ...payment, id: makeId() }))
  ];
  state.incomes = [
    ...state.incomes,
    ...imported.incomes.map((income) => ({ ...income, id: makeId() }))
  ];
}

function escapeHtml(value) {
  return String(value)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

document.addEventListener("click", (event) => {
  const actionTarget = event.target.closest("[data-action]");
  if (actionTarget) handleAction(actionTarget);

  const nav = event.target.closest("[data-view]");
  if (nav) {
    document.querySelectorAll(".nav-button").forEach((button) => button.classList.toggle("is-active", button === nav));
    Object.entries(views).forEach(([name, element]) => element.classList.toggle("is-active", name === nav.dataset.view));
  }
});

refreshButton.addEventListener("click", refreshDashboard);

document.addEventListener("submit", (event) => {
  const form = event.target;
  if (form.dataset.action === "adjust-balance") {
    event.preventDefault();
    adjustBalance(Number(new FormData(form).get("actualBalance") || 0));
  }

  if (form.dataset.action === "save-settings") {
    event.preventDefault();
    const data = new FormData(form);
    state.settings.hourlyRate = Number(data.get("hourlyRate") || 0);
    state.settings.averageDeliveriesPerHour = Number(data.get("averageDeliveriesPerHour") || 0);
    state.settings.maxDailyWorkHours = clampNumber(data.get("maxDailyWorkHours"), 0, 24);
    state.settings.maxWeeklyWorkDays = clampNumber(data.get("maxWeeklyWorkDays"), 0, 7);
    state.settings.warningThreshold = Number(data.get("warningThreshold") || 0);
    state.backup.reminderDays = clampNumber(data.get("backupReminderDays"), 0, 90);
    saveAndRender();
  }
});

entryForm.addEventListener("submit", (event) => {
  if (event.submitter?.value !== "save") return;
  event.preventDefault();
  const type = document.querySelector("#entryType").value;
  const id = document.querySelector("#entryId").value;
  const item = {
    id: id || makeId(),
    name: document.querySelector("#entryName").value.trim(),
    amount: Number(document.querySelector("#entryAmount").value || 0),
    date: document.querySelector("#entryDate").value
  };

  const collection = type === "payment" ? state.payments : state.incomes;
  const index = collection.findIndex((entry) => entry.id === id);
  if (type === "payment") item.status = index >= 0 ? collection[index].status : "planned";
  if (index >= 0) collection[index] = item;
  else collection.push(item);

  entryDialog.close();
  saveAndRender();
});

importFile.addEventListener("change", async () => {
  const file = importFile.files[0];
  if (!file) return;
  try {
    const imported = JSON.parse(await file.text());
    pendingImportState = normalizeState(imported);
    importDialog.showModal();
  } catch {
    alert("JSONの読み込みに失敗しました。");
  } finally {
    importFile.value = "";
  }
});

importModeForm.addEventListener("submit", (event) => {
  const mode = event.submitter?.value;
  if (!pendingImportState || mode === "cancel") {
    pendingImportState = null;
    return;
  }

  if (mode === "replace") {
    if (!confirm("現在のデータをすべて削除し、JSONの内容に置き換えます。実行しますか？")) {
      pendingImportState = null;
      return;
    }
    state = pendingImportState;
    showToast("データを上書き読込しました");
  }

  if (mode === "append") {
    appendImportedData(pendingImportState);
    showToast("支払い・入金予定を追記しました");
  }

  pendingImportState = null;
  saveAndRender();
});

render();
